### PR TITLE
Update deprecated functions

### LINKED ISSUE #33: Update deprecated functions
Hi @krlmlr, would you like a hand to update deprecated functions in the package? :) 

For example:
```r
#> `kimisc::ofactor()` is deprecated, use `forcats::fct_inorder()` instead.
#> Warning: `select_()` was deprecated in dplyr 0.7.0.
#> Please use `select()` instead.
#> Warning: `mutate_()` was deprecated in dplyr 0.7.0.
#> Please use `mutate()` instead.
#> See vignette('programming') for more help
#> Warning: `data_frame()` was deprecated in tibble 1.1.0.
#> Please use `tibble()` instead.
#> Warning: `group_by_()` was deprecated in dplyr 0.7.0.
#> Please use `group_by()` instead.
```

### PR DESCRIPTION
**Pull request by asiripanich**
This PR closes #33. 

```r
r$> devtools::test()                                                      
Loading MultiLevelIPF
Testing MultiLevelIPF
✔ |  OK F W S | Context
✔ |  66       | algorithms [5.1 s]                                        
✔ |  92       | Corner cases [4.9 s]                                      
✔ |   1       | correlating [0.2 s]                                       
✔ |  16       | flatten [1.0 s]                                           
✔ | 210       | import [0.9 s]                                            
✔ |   1       | missing_level [0.1 s]                                     
✔ |  44       | return [1.7 s]                                            
✔ |   4       | toy [0.1 s]                                               
✔ |   4       | utils                                                     

══ Results ═══════════════════════════════════════════════════════════════
Duration: 14.3 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 438 ]
```

### CODE REVIEW

**Comment by asiripanich** [comment]
@krlmlr would you like me to use `#' @importFrom rlang .data` to fix the 'visible binding for global variable' notes?

**Comment by krlmlr** [comment]
Yeah, let's try the `.data` prefix here.

**Comment by asiripanich** [comment]
Please update the version and NEWS before merging :).

**Comment by krlmlr** [comment]
Thanks! I'm using fledge to update NEWS and DESCRIPTION every one in a while; we could also automate this if this is a use case for you (https://github.com/cynkra/fledge/issues/84).

Are you relying on unique package versions in `DESCRIPTION`?

**Comment by asiripanich** [comment]
Would be great if we can set that up. :) Let me know how I can help.

  > Are you relying on unique package versions in DESCRIPTION?

Not any at the moment.

By the way, I have been using your MultiLevelIPF for a long time and I'm sure there are a few others as well. Are you ever going to put this package on CRAN?

**Comment by krlmlr** [comment]
Thanks, glad you find it useful. For a CRAN release, we need to:

- inline the code from the grake package (there's no longer a merit in two separate packages)
- go over the documentation, add at least breadcrumbs how to get started using it, if not a tutorial

Would you like to help?

I don't mind managing the NEWS file for now, we'll figure out details later.

**Comment by asiripanich** [comment]
Yes, I would like to help to make the package ready for CRAN submission. :)

I will open new issues for those tasks so we can keep track of things.

**Pull request merged**
